### ISSUE TITLE
Uploading latest OCHEM predictions to GitHub?

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#10]
There are quite a number of new classes in ChEBI. Release 189 should be out tomorrow (July 1). Could we run the OCHEM predictions for all new classes in this release?

I think it would be appreciated if we could update the predictions at least every six months on GitHub.

**Comment by magnuspalmblad** [comment]
Now works.

**Comment by magnuspalmblad** [comment]
So this doesn't work yet? :)


Cheers,

Magnus

________________________________

**Comment by ReinV** [comment]
It works but I noticed that the files on this github are not from the latest ChEBI release. So I thought to reopen this issue as a reminder to upload them.
