### ISSUE TITLE
TFIDF changes numbers displayed in table

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#12]
Applying TFIDF in the SCOPE plot changes the color mapping but also changes the numbers displayed in the table. The numbers displayed in the table should still be the raw counts, before normalization.

**Comment by ReinV** [comment]
What about the top ChEBI identifiers? These are the top 3 most common ChEBI's that appeared in the search. These might change after applying TFIDF. Should this be unchanged after selecting TFIDF? Currently, the all tooltip info is changed after TFID.

**Comment by magnuspalmblad** [comment]
Valid point. As long as we clearly document the behavior, I think the user will be OK with it. How about showing the original numbers, even if the order (or the ChEBIs) change after TFIDF? I worry that someone may report the number after TFIDF as the number of occurrences of the ChEBI in the corpus.

More complicated, but perhaps we could add a column with the number of documents that is only shown when TFIDF is selected? Or the TFIDF value?

**Comment by ReinV** [comment]
Number of documents or number of appearances? An additional column with TFIDF information should not be difficult to implement and might be preferable over a changing tooltip table!

**Comment by ReinV** [comment]
> only shown when TFIDF is selected? Or the TFIDF value?

Ah I misunderstood. So then we still have a changing tooltip. Why not have this column always in the tooltip table?

**Comment by magnuspalmblad** [comment]
Yes, that may actually be more clear. The number of documents may still be of interest, even when not in TFIDF "mode".

**Comment by magnuspalmblad** [comment]
This has now been fixed.
