### ISSUE TITLE
Underscores ('_') not allowed in search query or file names?

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#16]
I keep getting errors if I use underscores in the search query names. Apparently, the scripts splits filenames to remove the '_table' and similar. Generally, underscores are assumed to be safe in filenames, unlike spaces. Even if we want to add '_table' to a filename and later parse it using split, it is possible to do this by parsing from the end of the filename.

When making a search named "NOT_COVID-19", the following happens:

```
...
19000/19251 publications retrieved
20000/19251 publications retrieved
NOT_COVID-19 query results are written to file
8161 publications with text mined terms and annotations of type 'chemical' found for NOT_COVID-19

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>python make_table.py -i results -t folder
getting searches by year ...
results\COVID-19_ChEBI_IDs.tsv
making table for COVID-19
results\NOT_COVID-19_ChEBI_IDs.tsv
making table for NOT
```

**Comment by ReinV** [comment]
Should be fixed now.
