### ISSUE TITLE
Add summary statistics (moments) of mass and log P distributions

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#18]
This is a suggestion, but a user may wish to summarize a number of analyses/results (for example of analytical chemistry methods) in a table. Information that may then be informative would be the univariate means and standard deviations of mass and log P. Obviously these do not convey all information, but may nevertheless be better than nothing in a tabular overview of results.

These numbers could be put in the metadata popup window, but I wonder if it would be better to add a button under metadata that says "analytics", "statistics", or similar.

**Comment by ReinV** [comment]
Good suggestion, this should not be difficult to implement and we can choose to add more (advanced) statistics later.

**Comment by ReinV** [comment]
@magnuspalmblad forgot to mention this but it's in the latest version of SCOPE.

**Comment by magnuspalmblad** [comment]
Excellent! Perhaps "Total amount" (as in "Total amount of chemicals:" should be "Total number of chemical entity recognitions" instead? "Amount" implies it could be a weight, or a physical amount.
