### ISSUE TITLE
Multiplot and query names truncated

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#19]
Only the 14-15 first characters of the name of the multiplot fit in the upper left corner. Similarly, only the first 7-8 characters of the individual query names fit. Would it be possible to add a side scroll or expansion of these fields, to reveal the full names? It may be a minor bug, but it could be very annoying if a user gives their queries very similar names, say "capillary electrophoresis" and "capillary electrochromatography".

**Comment by ReinV** [comment]
There is currently no side scroll available using Bokeh. Since the (full) query names are also shown in the plot title, the user can check longer names here to be sure. Would you agree that this is enough for now?

**Comment by magnuspalmblad** [comment]
Yes!
