### ISSUE TITLE
Error running update_chebis.py

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#21]
When running update_chebis.py, I get the following error:

```
(base) G:\Projects\COVID-19\2021\SCOPE\SCOPE-master>python update_chebis.py
Importing latest ontology...
ChEBI version used to update files: 189
ChEBI latest version: 195
Files need updating ...
[...]
{'status': 'success', 'taskId': 1147255, 'metaserverTaskId': 36550772}
200 9000 0 9200
Getting predictions 9200 to 9400
{'status': 'success', 'taskId': 1147256, 'metaserverTaskId': 36550773}
43 9243 157 9243
{'status': 'success', 'taskId': 1147257, 'metaserverTaskId': 36550774}
Model predictions are still pending: request repeated in 10 seconds ...
Model predictions failed, script stopped
```

The ChEBIs listed include some very long ones, and some with asterisks, but I assume the latter is no longer a problem. Is the issue with the Python script or the OCHEM server?

**Comment by ReinV** [comment]
In my experience, sometimes the issue is with OCHEM. So please try again a few times just to be sure. 

If I look at the numbers, it failed at the last batch! If the script crashes again on the last batch, we need to investigate it. I will make sure to run update_chebis.py as well.

**Comment by ReinV** [comment]
I got one failed run and one succesful run. Did you make sure to run the latest version of update_chebis.py?

**Comment by magnuspalmblad** [comment]
I thought I had the latest version, but I also got a successful run, after updating. Closing this issue, as there is probably nothing wrong with update_chebis.py.
