### ISSUE TITLE
python search_query.py -i queries/ does not work for me

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#26]
When running the `search_query.py` script in my Anaconda shell (under Windows 10), I cannot run it without specifying one input file. This is how it is supposed to be, right? If so, please amend the instructions.

This is the specific error I get: 
```
(base) C:\Users\nmpalmblad\Downloads\SCOPE-master>python search_query.py -i queries/
Traceback (most recent call last):
  File "search_query.py", line 215, in <module>
    main()
  File "search_query.py", line 206, in main
    queries = read_input(input_file)
  File "search_query.py", line 181, in read_input
    f = open(file, 'r')
PermissionError: [Errno 13] Permission denied: 'queries/'
```

**Comment by ReinV** [comment]
Indeed, an input file should be provided. This is correctly noted in the help function of the script, but not in the README file. Apparently <input text file> is removed in the README because it is seen as an <input> argument, and I didn't notice. Should be fixed now.
