### ISSUE TITLE
download_files.py slow or stalled

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#29]
When running the download_files.py script, it appears the downloads stall at 2010-2019_ChEBI_IDs.tsv. I could download this file from osf.io, and it took just under a minute. But the script has worked for more than 2 hours on this file now. Is this something you have seen too? Is OSF throttling the download, or is the script stalled?

This is my output:

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master>python download_files.py
ChEBI2Class.pkl
ChEBI2logP.tsv
ChEBI2Mass.tsv
ChEBI2logS.tsv
ChEBI2logS.tsv
ChEBI2Names.tsv
ChEBI2Smiles.tsv
2020-2029_ChEBI_IDs.tsv
2010-2019_ChEBI_IDs.tsv
```

**Comment by magnuspalmblad** [comment]
FYI, the file is currently 25 MB, and the 2020-2029 file 0 bytes.

**Comment by ReinV** [comment]
No, it's also downloaded in a minute when I run the script and in the correct folder.

**Comment by ReinV** [comment]
Can you rerun the script and see if it happens again? (delete the files and searches folder first). If so, then we need to add some lines and do some testing to see what is happening.

**Comment by magnuspalmblad** [comment]
I am rerunning it now, and realized I had to delete the two folders first. The behavior I expected was that it would just download these again and overwrite the existing files. (An even more elegant solution would be to check if the local files are different than the files on ostf.io.)

**Comment by ReinV** [comment]
The script now checks if the folders exist and if so, it does nothing. I guess this is not the most obvious behaviour but it works when new users pull from github and then run the script.

**Comment by ReinV** [comment]
Yes! I guess we should at least add a "download completed" print statement. My plan was to see if this also works for you, than we can add the rest later to the downloads.
