### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#3]
ChEBI is written with all caps except the 'h'. Perhaps we should rename the project to "ChEBI2plot"? Or maybe you could come up with a catchier name?

**Comment by ReinV** [comment]
I agree that we should come up with a catchier name,! Let's think about that, but for now I will just rename the project.

**Comment by magnuspalmblad** [comment]
Thinking about the name, some keywords are ChEBI, ontology, literature, text mining, Europe PMC, plot, visualization, patterns, interaction, interface, browser, plus/+ (adding functionality to Europe PMC - there is already a Europe PMC plus service)

Of course, one can also use a completely random name.

The best I've come up with so far 'SCOOP' for 'Search and Chemical OntoOlogy Plot' and 'SCOPE' for 'Search and Chemical Ontology Plotting Environment'.

Thoughts?

**Comment by ReinV** [comment]
I really like the 'SCOPE' name. Can we still call it a toolbox even if the toolbox is not in the name?

**Comment by magnuspalmblad** [comment]
Yes! We can use 'SCOPE toolbox' when referring to the set of Python scripts. The "environment" could be understood to also include the data tables and web browser, perhaps also the Europe PMC and OCHEM web services. But we do not need to explicitly list everything that is in the "environment".

**Comment by magnuspalmblad** [comment]
I changed the Gaussian blur manuscript to "SCOPE". I like the name more and more, as it suggests looking at something (as with microscopes and telescopes). As a verb it also means "assess or investigate something" or "scan". Could you change it on here?

**Comment by ReinV** [comment]
I agree. Name is now changed!
