### ISSUE TITLE
Only first plot in multiplot is rendered in browser?

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#33]
I now managed to get all the way to the multiplots. However, only the first search is visualized. The older HTML multiplots work fine in the same browser (have tried Chrome, Firefox and Edge). You can find a small example [here](https://drive.google.com/file/d/1jFrDE2Yl6cKkee8q4QGtqha3LKFAN5ud/view?usp=sharing).

Any idea what could be wrong? I did not get any error messages running the Python scripts.

**Comment by ReinV** [comment]
Should be fixed now.
