### ISSUE TITLE
GUI or workflow for running all scripts

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#34]
It would be a good idea to combine the Python scripts in a simple GUI, notebook or workflow.

**Comment by ReinV** [comment]
What about Snakemake?

**Comment by magnuspalmblad** [comment]
Yes, Snakemake is quite popular in the Python world. Jupyter notebooks are also common, and then you do not need to change the code at all (and we could also insert some R code if we want, using rpy2. Either one would be fine I think.
