### ISSUE TITLE
Programming language percentages on the SCOPE github not correct.

### ISSUE THREAD

**Issue by ReinV** [ReinV/SCOPE#48]
It shows 99% HTML and 1% python. Most code is python.

**Comment by magnuspalmblad** [comment]
I have seen this in other projects as well. Could we tell GitHub to ignore the HTML by adding a .gitattributes file?

**Comment by magnuspalmblad** [comment]
Alternatively, perhaps we can move the HTML plot to the OSF project instead?

**Comment by ReinV** [comment]
This was indeed the issue. Thanks for the suggestion. HTML plot is on OSF.
