### ISSUE TITLE
Showing class/superterm

### ISSUE THREAD

**Issue by ReinV** [ReinV/SCOPE#6]
It would be possible to have a  (not required) -class argument that, when given, plots chemicals from that class with a different color (pink or red) (maybe with a on/off button ). 

Should only the chemicals of the query from that class/superterm be plotted or all ChEBI identifiers in the ontology from that class/superterm?

**Comment by magnuspalmblad** [comment]
Absolutely - aggregating and displaying properties of particular higher-level chemical classes is highly relevant and informative! Pink/red stands out on both Viridis and grayscale. On-off button like TF-IDF is good too (active only when class information is available).

**Comment by ReinV** [comment]
Script can now recieve -class argument. If no class argument is given, no checkbox will be shown. Could you give it a try and see if it works like expected?

**Comment by ReinV** [comment]
Script can now recieve -class argument. If no class argument is given, no checkbox will be shown. Could you give it a try and see if it works like expected?

**Comment by magnuspalmblad** [comment]
The check button appears, but if there are no members of the superclass in the query results (input table), nothing is shown. I would have expected that it would show all members of the class in ChEBI. Even with 'gas chromatography', I do not see any alkanes (18310).

In the interface, it would be nicer to see the ChEBI name first, than the ChEBI ID within parentheses. But perhaps some names are very long?

**Comment by magnuspalmblad** [comment]
There were quite a few alkanes in those results, and 18310 is in the tables.  I tried some leaf nodes (individual compounds) that were in the results, but nothing, nada, zilch, diddly, aught, zippo!

**Comment by ReinV** [comment]
>  I would have expected that it would show all members of the class in ChEBI.

Ah my mistake, I thought it would be nice to just show the members for that specific class in the query results. But you think it should show all ChEBI identifiers of that class regardless of the query search?

> I would have expected that it would show all members of the class in ChEBI. Even with 'gas chromatography', I do not see any alkanes (18310)

Did you give -class alkane or -class alkanes ?

The official ChEBI name is alkane and so -class alkanes should not give any results.

**Comment by magnuspalmblad** [comment]
Aha! You made it more user-friendly than I expected. I typed in the ID rather than the name! Now it works! Beautiful!

**Comment by magnuspalmblad** [comment]
Should the class be affected by the scaling and blur? Scaling would have a minor effect, but sometimes there are multiple members of the same class in the same bin. Blurring obviously have an effect. I am not suggesting it can be scaled or blurred separately, just follow how the data is scaled and blurred.

**Comment by ReinV** [comment]
That's a good question. I guess it should ... but that would require a sperate, slightly adjusted blurring function, because right now it is written for specific kind of dataframes. 

If it's okay with you I will leave it on the to do list and let this issue open for now.

**Comment by magnuspalmblad** [comment]
Absolutely!

**Comment by magnuspalmblad** [comment]
Problem solved. Closing issue.
