### ISSUE TITLE
Error running make_table.py

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#8]
I ran a search for "COVID-19". The results file looks OK as far as I can tell. But when I try to build the table, I get this error message:

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>make_table.py -i results -t folder
...
searches_by_year/2015_ChEBI_IDs.tsv
searches_by_year/2016_ChEBI_IDs.tsv
searches_by_year/2017_ChEBI_IDs.tsv
searches_by_year/2018_ChEBI_IDs.tsv
searches_by_year/2019_ChEBI_IDs.tsv
searches_by_year/2020_ChEBI_IDs.tsv
searches_by_year/pre1945_ChEBI_IDs.tsv
perform normalization...
reading files with properties...
Traceback (most recent call last):
  File "C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master\make_table.py", line 203, in <module>
    main()
  File "C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master\make_table.py", line 192, in main
    data = read_file(file, key, data)
  File "C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master\make_table.py", line 115, in read_file
    info = line_to_list[1].strip()
IndexError: list index out of range
```

Any idea what I am doing wrong? Running it in file mode, I get:

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>make_table.py -i results/COVID-19_ChEBI_IDs.tsv -t file
Traceback (most recent call last):
  File "C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master\make_table.py", line 203, in <module>
    main()
  File "C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master\make_table.py", line 166, in main
    id_to_counts, id_to_publications, term = read_input(result)
  File "C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master\make_table.py", line 83, in read_input
    term = file.split('\\')[1].split('_')[0]
IndexError: list index out of range
```

**Comment by ReinV** [comment]
Try backslash in stead of forward slash: results\COVID-19_ChEBI_IDs.tsv

**Comment by magnuspalmblad** [comment]
Same result. I use the Anaconda prompt which handles both / and \. Could it be a missing library?

**Comment by ReinV** [comment]
Ah my bad. In the first post there are 2 different errors. I'm guessing the last error in the post should be fixed by replacing forward slash with backward slash. The first error however occurs when reading the ChEBI files in the 'files' folder. Before we start adding print statements, could you check if all the files are in place and look OK? ('files/ChEBI2Names.tsv', 'files/ChEBI2Mass.tsv', 'files/ChEBI2logP.tsv', 'files/ChEBI2Superterms.tsv')

**Comment by magnuspalmblad** [comment]
They seem to be there - but perhaps there are some new ChEBIs in the results? Though that shouldn't cause an error, right? Changing the / to a \ in the files mode does not seem to make any difference.

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>ls files -l
total 20145
-rw-rw-rw-   1 user     group     1782232 Jun  3 14:04 ChEBI2Mass.tsv
-rw-rw-rw-   1 user     group     7881882 Jun  3 14:04 ChEBI2Names.tsv
-rw-rw-rw-   1 user     group     8388813 Jun  3 14:04 ChEBI2Smiles.tsv
-rw-rw-rw-   1 user     group         133 Jun  3 14:04 ChEBI2Superterms.tsv
-rw-rw-rw-   1 user     group         133 Jun  3 14:04 ChEBI2Superterms_roles.tsv
-rw-rw-rw-   1 user     group     1250531 Jun  3 14:04 ChEBI2logP.tsv
-rw-rw-rw-   1 user     group     1232289 Jun  3 14:04 ChEBI2logS.tsv
-rw-rw-rw-   1 user     group       85492 Jun  3 14:04 new_smiles.txt
-rw-rw-rw-   1 user     group           3 Jun  3 14:04 ontology_version.txt

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>
```

The ChEBI2Superterms.tsv and ChEBI2Superterms_roles.tsv seem a bit small though...

**Comment by ReinV** [comment]
> Changing the / to a \ in the files mode does not seem to make any difference.
I think that should fix this error:
```
    term = file.split('\\')[1].split('_')[0]
IndexError: list index out of range
```
This line expects a \ in the filename.

But it will not fix this error:
```
    info = line_to_list[1].strip()
IndexError: list index out of range
```

Because this is the error that is caused when reading the ChEBI files. 

Could you check the file ChEBI2Superterms.tsv, particularly the end of the file? If I remember correctly we had a similar problem before when downloading this file from github. Because it is larger than 50MB, something strange happens and you get some strange output lines at the end of the file. This could explain the error when reading this file.

**Comment by magnuspalmblad** [comment]
Right - it seems those files (stored on the GitHub LTS) have to be downloaded individually. When downloaded with the project, you only get the version number, OID sha256 and file size:

version https://git-lfs.github.com/spec/v1
oid sha256:704f8c4547ff00b4e92b068473638c4b75c6e3a1825f7b658c7d6fe7c7c33d7a
size 52828611

I downloaded them now, and am running the OCHEM predictions for the ~5,000 new ChEBI entries. Did you already do this for the latest version? Perhaps we could update the GitHub with these? We also have all the searches_by_year, which perhaps could be combined into a single summary file to use for TFIDF?

**Comment by ReinV** [comment]
> Did you already do this for the latest version? Perhaps we could update the GitHub with these? 

Not for the latest, I can check and update later this week. 

> We also have all the searches_by_year, which perhaps could be combined into a single summary file to use for TFIDF?

I thought about this as well, maybe a file per decade ? Then for more fast results you can choose to only import latest decade. I'm guessing this makes it also easier for memory usage.

**Comment by magnuspalmblad** [comment]
OK, with the correct and complete files in the "files" folder, it works. So my bad for not remembering these are not downloaded with the rest of the files in the repository. I will close the issue, as I am also running the prediction of the new ChEBI entries on the server now.
