### ISSUE TITLE
visualize_multiplot.py -class argument does not work with has_role classes

### ISSUE THREAD

**Issue by magnuspalmblad** [ReinV/SCOPE#9]
I noticed that visualize_multiplot.py with the -class argument does not work with (all) classes. I have looked at "antiviral agent", "antiviral drug" and just "drug". They are found by count_classes.py, and other classes, such as "ureas" visualize just fine.

Here is what I did:

```
(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>count_classes.py -i tables\COVID-19_table.tsv -c 23888
looking for ChEBI class drug with id 23888
total count of 23888: 480819
chemicals with class 23888: 3226

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>visualize_multiplot.py -i tables -o COVID-19_drug -class drug
0:00:17.112826

(base) C:\Users\Magnus Palmblad\Downloads\SCOPE-master\SCOPE-master>
```

**Comment by ReinV** [comment]
For me, all of those classes work and are visualized on the map. Could you check if you used the right table (made with superterms_roles) to make the plot?

**Comment by magnuspalmblad** [comment]
OK, marking as solved.
